### ISSUE TITLE
Check in missing files

### ISSUE THREAD

**Issue by jchodera** [openforcefield/MiniDrugBank#14]
@bannanc : The [pickMolecules.ipynb](https://github.com/openforcefield/MiniDrugBank/blob/master/minidrugbank/pickMolecules.ipynb) notebook references files like "molecules/DrugBank_ff.mol2" which are not included in this repo. Can you add them?

**Comment by bannanc** [comment]
I will add them, but they're also in openforcefield/data/molecules/ if you
need them ASAP.
-- 
*****************************************
Caitlin C. Bannan
Ph.D. Candidate
Mobley Group
UC Irvine - Chemistry Department
bannanc@uci.edu
mobleylab.org

**Comment by bannanc** [comment]
@davidlmobley and I discussed this in person. In our opinion, part of the benefit of this repository is to not have to download all of DrugBank. If people want to run that notebook they shouldn't need the file locally because openforcefield toolkits will look into its `data/molecules/` directory where that file is permanently stored.
